# Generated by Django 5.1 on 2024-08-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerce_Site', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
